name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou master, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # A pasta raiz contendo seu site HTML
          branch: gh-pages  # A branch onde o site será publicado
          clean: true  # Remove arquivos antigos
          token: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticação

      - name: Status do deploy
        run: echo "Site implantado com sucesso em https://$(echo ${{ github.repository_owner }}).github.io/design-for-failure/"
