name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Permissões necessárias para publicação
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4
      
      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
          token: ${{ secrets.DEPLOY_TOKEN }} 
          commit-message: "Deploy da apresentação - ${{ github.event.head_commit.message }}"
